### ISSUE TITLE
Question about table creation

### ISSUE THREAD

**Issue by mpicard** [bloom42/goes#4]
I like what you've made here, very nice interfaces. I tried running the example/user with a clean DB there is obviously no user table and it doesn't look like `goes` is doing gorm `AutoMigrate`, what's the necessary table definitions for all the tables that `goes` would need?

**Comment by z0mbie42** [comment]
Hi,
Thanks for pointing this out, I've added the file https://github.com/bloom42/goes/blob/master/examples/user/setup_db.go to help the Database setup.

I've also updated the example which was a little bit outdated (missing interface methods).

**Comment by mpicard** [comment]
Thanks @z0mbie42 that's really nice, I was wondering if it would be possible to AutoMigrate the "____s_events" table somehow? I'm running:

      goes.DB.AutoMigrate(&User{})

**Comment by z0mbie42** [comment]
Hi,
Using `AutoMigrate` is not really a good practice so you should avoid it and instead use tools like https://github.com/golang-migrate/migrate - https://github.com/pressly/goose - https://github.com/diesel-rs/diesel which allow schema versioning, and schema rollback

**Comment by mpicard** [comment]
Ah ok thanks I will take a look at those. Also would you mind adding a bit more examples such as SyncReactors and AsyncReactors and maybe the best practice to query? Would it be ok to use `goes.Store` to directly query?

**Comment by z0mbie42** [comment]
I've added both `SyncReactor` and `AsyncReactor` exmaples in both the README and the user example.

to query the aggregate store or the event store (which are the same database) you can use `goes.DB` (an example was also added). `goes.Store` is just a type alias.
