### ISSUE TITLE
Subscriptions out of the other end

### ISSUE THREAD

**Issue by gedw99** [bloom42/goes#5]
I want to use this for apps where the apps can subscribe to CRUD changes on the aggregates.

This is a very powerful way to build apps because you don't need complex flux / blab / blab patterns on the front end app.

I am flagging this idea to see if there is interest.
It's an exceedingly simple pattern that I find is fantastic with a simple ES system like GOES !

If I did a terrible description of the why and what above please ask.

I already have an idea of how to do ..

**Comment by z0mbie42** [comment]
something like firestore (https://firebase.google.com/docs/firestore/) ?

**Comment by gedw99** [comment]
hey @z0mbie42 
yep as far as i know it is similar to firestore. I have not used it however.

There is a small bit of generic logic on the client that just has to check what type of CRUD it is, and then modify the cached list accordingly for each "aggregate view model".

When the client first opens, you have two choices architecturally:
1. Reload everything needed from the server. So your the leaving the aggregates view model is not saved at all, but instead just saved in memory during normal running.
2. If you cached the aggregates on disk, ask the server for any updates that the client missed out on whilst it was offline / away.

With both option 1 or 2, the easiest way is to have a mailbox per user. I have seen NATS used for this. But i think GOES does not need that because there is no complex sub / pub, because you always just have a client viewModel map one to one to the server side aggregate.

The ONLY difference between 1 and 2, is that with 1 the mailbox is in memory, and with 2, the mailbox is durable on disk.

So, if you default to durable on disk mailbox, you can decide to do option 1 or 2 on the client as you see fit.

Hope i am explaining myself well ?

**Comment by z0mbie42** [comment]
I would really live to see such a project emerging but it's unfortunately too far out of the scope of goes (mainly a thin ES layer on top of a postgres compatible database). 

Such a project imply transport management, authorization, authentication ...

It would be really cool to see such a project but it's far too complex for goes.
